[ 2024-04-23 23:02:48,010 ] 94 root - INFO - Starting all threads
[ 2024-04-23 23:02:48,010 ] 94 root - INFO - Starting all threads
[ 2024-04-23 23:02:48,010 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Hirabari', 'test_mode': False, 'onlyday': False, 'max_num_retry': 5, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-23 23:02:48,010 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Hirabari', 'test_mode': False, 'onlyday': False, 'max_num_retry': 5, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-23 23:02:48,011 ] 94 root - INFO - Number of dev accounts: 3
[ 2024-04-23 23:02:48,011 ] 94 root - INFO - Number of dev accounts: 3
[ 2024-04-23 23:02:48,014 ] 94 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-23 23:02:48,015 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: nihahi50@gmail.com, Password: hoahong1234
[ 2024-04-23 23:02:50,016 ] 94 root - INFO - Thread 0 started
[ 2024-04-23 23:02:50,016 ] 94 root - INFO - Thread 0 started
[ 2024-04-23 23:02:50,018 ] 94 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-23 23:02:50,018 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: ble79037@gmail.com, Password: hoahong1234
[ 2024-04-23 23:02:50,902 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 23:02:52,029 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 23:02:52,033 ] 94 root - INFO - Thread 1 started
[ 2024-04-23 23:02:52,033 ] 94 root - INFO - Thread 1 started
[ 2024-04-23 23:02:52,087 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-23 23:02:52,088 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: benemmai380@gmail.com, Password: hoahong1234
[ 2024-04-23 23:02:54,098 ] 94 root - INFO - Thread 2 started
[ 2024-04-23 23:02:54,098 ] 94 root - INFO - Thread 2 started
[ 2024-04-23 23:02:55,879 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 23:02:57,778 ] 94 nihahi50 - INFO - Opened login page
[ 2024-04-23 23:02:59,054 ] 94 ble79037 - INFO - Opened login page
[ 2024-04-23 23:03:02,863 ] 94 benemmai380 - INFO - Opened login page
[ 2024-04-23 23:03:03,906 ] 82 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-23 23:03:03,925 ] 94 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-23 23:03:04,558 ] 94 ble79037 - INFO - Logging in
[ 2024-04-23 23:03:04,571 ] 94 ble79037 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 23:03:04,889 ] 94 ble79037 - INFO - Logged in finished
[ 2024-04-23 23:03:04,889 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 23:03:04,999 ] 94 nihahi50 - INFO - Logging in
[ 2024-04-23 23:03:05,008 ] 94 nihahi50 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 23:03:05,226 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\23_02_47\screenshot_ble79037.png
[ 2024-04-23 23:03:05,233 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 23:03:05,239 ] 94 ble79037 - INFO - On main page
[ 2024-04-23 23:03:05,338 ] 94 nihahi50 - INFO - Logged in finished
[ 2024-04-23 23:03:05,339 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 23:03:05,714 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\23_02_47\screenshot_nihahi50.png
[ 2024-04-23 23:03:05,715 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 23:03:05,803 ] 94 nihahi50 - INFO - On main page
[ 2024-04-23 23:03:06,337 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 23:03:06,899 ] 94 ble79037 - INFO - Search submitted
[ 2024-04-23 23:03:06,988 ] 94 ble79037 - INFO - Collected 20 forms
[ 2024-04-23 23:03:08,036 ] 94 ble79037 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 23:03:08,037 ] 94 ble79037 - INFO - ＜05月08日(水) 08:45～09:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96453 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453 - True
[ 2024-04-23 23:03:08,039 ] 94 ble79037 - INFO - ＜05月08日(水) 09:30～10:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96454 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454 - True
[ 2024-04-23 23:03:08,040 ] 94 ble79037 - INFO - ＜05月08日(水) 10:30～11:45＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96455 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96455 - True
[ 2024-04-23 23:03:08,040 ] 94 ble79037 - INFO - ＜05月08日(水) 12:45～13:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96456 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96456 - True
[ 2024-04-23 23:03:08,041 ] 94 ble79037 - INFO - ＜05月08日(水) 13:30～14:45＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96457 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96457 - True
[ 2024-04-23 23:03:08,041 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-23 23:03:08,042 ] 94 main_controller - INFO - Customers: [{'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205'}, {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101'}]
[ 2024-04-23 23:03:08,043 ] 94 main_controller - INFO - Customer info index 1: {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:03:08,044 ] 94 main_controller - INFO - Customer index 1: Tran Thi Le Lai, M, 19000101, 080-1583-0891, ベトナム
[ 2024-04-23 23:03:08,045 ] 94 ble79037 - INFO - Accessing form, template sequence: 96453
[ 2024-04-23 23:03:08,045 ] 94 ble79037 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453
[ 2024-04-23 23:03:08,403 ] 94 nihahi50 - INFO - Search submitted
[ 2024-04-23 23:03:08,534 ] 94 nihahi50 - INFO - Collected 20 forms
[ 2024-04-23 23:03:10,793 ] 94 nihahi50 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 23:03:10,794 ] 94 nihahi50 - INFO - ＜05月08日(水) 08:45～09:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96453 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453 - True
[ 2024-04-23 23:03:10,798 ] 94 nihahi50 - INFO - ＜05月08日(水) 09:30～10:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96454 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454 - True
[ 2024-04-23 23:03:10,799 ] 94 nihahi50 - INFO - ＜05月08日(水) 10:30～11:45＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96455 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96455 - True
[ 2024-04-23 23:03:10,801 ] 94 nihahi50 - INFO - ＜05月08日(水) 12:45～13:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96456 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96456 - True
[ 2024-04-23 23:03:10,802 ] 94 nihahi50 - INFO - ＜05月08日(水) 13:30～14:45＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96457 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96457 - True
[ 2024-04-23 23:03:10,803 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-23 23:03:10,804 ] 94 main_controller - INFO - Customers: [{'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205'}, {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}]
[ 2024-04-23 23:03:10,804 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:03:10,805 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:03:10,806 ] 94 nihahi50 - INFO - Accessing form, template sequence: 96454
[ 2024-04-23 23:03:10,806 ] 94 nihahi50 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454
[ 2024-04-23 23:03:12,236 ] 94 benemmai380 - INFO - Opened login page
[ 2024-04-23 23:03:14,171 ] 94 ble79037 - INFO - Accessed form successfully
[ 2024-04-23 23:03:14,188 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:14,189 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 1, template sequence: 96453
[ 2024-04-23 23:03:15,787 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:15,787 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 2, template sequence: 96453
[ 2024-04-23 23:03:16,210 ] 94 benemmai380 - INFO - Logging in
[ 2024-04-23 23:03:16,218 ] 94 benemmai380 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 23:03:16,424 ] 94 nihahi50 - INFO - Accessed form successfully
[ 2024-04-23 23:03:16,441 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:16,442 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 1, template sequence: 96454
[ 2024-04-23 23:03:16,538 ] 94 benemmai380 - INFO - Logged in finished
[ 2024-04-23 23:03:16,539 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 23:03:16,795 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\23_02_47\screenshot_benemmai380.png
[ 2024-04-23 23:03:16,796 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 23:03:16,808 ] 94 benemmai380 - INFO - On main page
[ 2024-04-23 23:03:17,201 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:17,201 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 3, template sequence: 96453
[ 2024-04-23 23:03:18,448 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:18,448 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 2, template sequence: 96454
[ 2024-04-23 23:03:18,645 ] 94 benemmai380 - INFO - Search submitted
[ 2024-04-23 23:03:18,692 ] 94 benemmai380 - INFO - Collected 20 forms
[ 2024-04-23 23:03:18,711 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:18,712 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 4, template sequence: 96453
[ 2024-04-23 23:03:19,167 ] 94 benemmai380 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 23:03:19,167 ] 94 benemmai380 - INFO - ＜05月08日(水) 08:45～09:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96453 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453 - True
[ 2024-04-23 23:03:19,168 ] 94 benemmai380 - INFO - ＜05月08日(水) 09:30～10:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96454 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454 - True
[ 2024-04-23 23:03:19,168 ] 94 benemmai380 - INFO - ＜05月08日(水) 10:30～11:45＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96455 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96455 - True
[ 2024-04-23 23:03:19,169 ] 94 benemmai380 - INFO - ＜05月08日(水) 12:45～13:30＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96456 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96456 - True
[ 2024-04-23 23:03:19,169 ] 94 benemmai380 - INFO - ＜05月08日(水) 13:30～14:45＞[平針]外国免許切替審査 Hirabari Exchanging Foreign Driver's License - 近日受付開始 - 2024年04月24日 07時30分 - 2024年05月02日 12時00分 - 96457 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96457 - True
[ 2024-04-23 23:03:19,169 ] 94 main_controller - INFO - Found 5 form(s)
[ 2024-04-23 23:03:19,170 ] 94 main_controller - INFO - Customers: [{'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}, {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}]
[ 2024-04-23 23:03:19,170 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:03:19,170 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:03:19,171 ] 94 benemmai380 - INFO - Accessing form, template sequence: 96454
[ 2024-04-23 23:03:19,171 ] 94 benemmai380 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454
[ 2024-04-23 23:03:20,196 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:20,198 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 5, template sequence: 96453
[ 2024-04-23 23:03:20,242 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:20,244 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 3, template sequence: 96454
[ 2024-04-23 23:03:21,434 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:21,434 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 6, template sequence: 96453
[ 2024-04-23 23:03:21,650 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:21,651 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 4, template sequence: 96454
[ 2024-04-23 23:03:23,299 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:23,299 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 7, template sequence: 96453
[ 2024-04-23 23:03:23,522 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:23,523 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 5, template sequence: 96454
[ 2024-04-23 23:03:24,838 ] 94 benemmai380 - INFO - Accessed form successfully
[ 2024-04-23 23:03:24,858 ] 94 benemmai380 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:24,859 ] 94 benemmai380 - INFO - Refreshing page to check availability trial number 1, template sequence: 96454
[ 2024-04-23 23:03:25,004 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:25,005 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 6, template sequence: 96454
[ 2024-04-23 23:03:25,068 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:25,068 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 8, template sequence: 96453
[ 2024-04-23 23:03:26,546 ] 94 benemmai380 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:26,546 ] 94 benemmai380 - INFO - Refreshing page to check availability trial number 2, template sequence: 96454
[ 2024-04-23 23:03:26,841 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:26,842 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 7, template sequence: 96454
[ 2024-04-23 23:03:27,157 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:27,158 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 9, template sequence: 96453
[ 2024-04-23 23:03:28,013 ] 94 benemmai380 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:28,013 ] 94 benemmai380 - INFO - Refreshing page to check availability trial number 3, template sequence: 96454
[ 2024-04-23 23:03:28,551 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:28,552 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 10, template sequence: 96453
[ 2024-04-23 23:03:28,662 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:28,663 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 8, template sequence: 96454
[ 2024-04-23 23:03:29,366 ] 94 benemmai380 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:29,366 ] 94 benemmai380 - INFO - Refreshing page to check availability trial number 4, template sequence: 96454
[ 2024-04-23 23:03:29,995 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:29,997 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 11, template sequence: 96453
[ 2024-04-23 23:03:30,385 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:30,386 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 9, template sequence: 96454
[ 2024-04-23 23:03:31,102 ] 94 benemmai380 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:31,104 ] 94 benemmai380 - INFO - Refreshing page to check availability trial number 5, template sequence: 96454
[ 2024-04-23 23:03:31,766 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:31,767 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 12, template sequence: 96453
[ 2024-04-23 23:03:32,177 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:32,180 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 10, template sequence: 96454
[ 2024-04-23 23:03:32,578 ] 82 benemmai380 - ERROR - Failed to get form message, maybe form is available
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 113, in get_form_message
    message = browser.find_element(By.XPATH, "/html/body/main/div/form/div[3]/strong/ul/li/span/strong").text
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:03:32,583 ] 94 benemmai380 - INFO - Form is available, template sequence: 96454
[ 2024-04-23 23:03:32,585 ] 94 benemmai380 - INFO - Filling form, template sequence: 96454
[ 2024-04-23 23:03:32,595 ] 82 benemmai380 - ERROR - Failed to click continue button: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 57, in fill
    continue_button = browser.find_element(By.XPATH, r'//*[@id="ok"]')
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:03:32,604 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96454
[ 2024-04-23 23:03:32,606 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:03:32,607 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:03:32,608 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:03:32,609 ] 94 benemmai380 - INFO - Accessing form, template sequence: 96457
[ 2024-04-23 23:03:32,609 ] 94 benemmai380 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96457
[ 2024-04-23 23:03:33,301 ] 94 ble79037 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:33,301 ] 94 ble79037 - INFO - Refreshing page to check availability trial number 13, template sequence: 96453
[ 2024-04-23 23:03:33,864 ] 94 nihahi50 - INFO - Form message: 申込期間ではありません。
[ 2024-04-23 23:03:33,865 ] 94 nihahi50 - INFO - Refreshing page to check availability trial number 11, template sequence: 96454
[ 2024-04-23 23:03:34,227 ] 82 ble79037 - ERROR - Failed to get form message, maybe form is available
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 113, in get_form_message
    message = browser.find_element(By.XPATH, "/html/body/main/div/form/div[3]/strong/ul/li/span/strong").text
AttributeError: 'NoneType' object has no attribute 'text'
[ 2024-04-23 23:03:34,230 ] 94 ble79037 - INFO - Form is available, template sequence: 96453
[ 2024-04-23 23:03:34,231 ] 94 ble79037 - INFO - Filling form, template sequence: 96453
[ 2024-04-23 23:03:34,233 ] 82 ble79037 - ERROR - Failed to click continue button: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 57, in fill
    continue_button = browser.find_element(By.XPATH, r'//*[@id="ok"]')
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:03:34,234 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96453
[ 2024-04-23 23:03:34,234 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:03:34,234 ] 94 main_controller - INFO - Customer info index 1: {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:03:34,235 ] 94 main_controller - INFO - Customer index 1: Tran Thi Le Lai, M, 19000101, 080-1583-0891, ベトナム
[ 2024-04-23 23:03:34,235 ] 94 ble79037 - INFO - Accessing form, template sequence: 96456
[ 2024-04-23 23:03:34,235 ] 94 ble79037 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96456
[ 2024-04-23 23:03:35,198 ] 82 nihahi50 - ERROR - Failed to get form message, maybe form is available
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 113, in get_form_message
    message = browser.find_element(By.XPATH, "/html/body/main/div/form/div[3]/strong/ul/li/span/strong").text
AttributeError: 'NoneType' object has no attribute 'text'
[ 2024-04-23 23:03:35,200 ] 94 nihahi50 - INFO - Form is available, template sequence: 96454
[ 2024-04-23 23:03:35,200 ] 94 nihahi50 - INFO - Filling form, template sequence: 96454
[ 2024-04-23 23:03:35,203 ] 82 nihahi50 - ERROR - Failed to click continue button: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 57, in fill
    continue_button = browser.find_element(By.XPATH, r'//*[@id="ok"]')
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:03:35,204 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96454
[ 2024-04-23 23:03:35,205 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:03:35,205 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:03:35,205 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:03:35,206 ] 94 nihahi50 - INFO - Accessing form, template sequence: 96457
[ 2024-04-23 23:03:35,206 ] 94 nihahi50 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96457
[ 2024-04-23 23:04:38,757 ] 82 benemmai380 - ERROR - Failed to access form: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:04:38,761 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96457
[ 2024-04-23 23:04:38,761 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:04:38,761 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:04:38,761 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:04:38,762 ] 94 benemmai380 - INFO - Accessing form, template sequence: 96455
[ 2024-04-23 23:04:38,762 ] 94 benemmai380 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96455
[ 2024-04-23 23:04:40,391 ] 82 ble79037 - ERROR - Failed to access form: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:04:40,392 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96456
[ 2024-04-23 23:04:40,393 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:04:40,393 ] 94 main_controller - INFO - Customer info index 1: {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:04:40,393 ] 94 main_controller - INFO - Customer index 1: Tran Thi Le Lai, M, 19000101, 080-1583-0891, ベトナム
[ 2024-04-23 23:04:40,394 ] 94 ble79037 - INFO - Accessing form, template sequence: 96454
[ 2024-04-23 23:04:40,394 ] 94 ble79037 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454
[ 2024-04-23 23:04:41,437 ] 82 nihahi50 - ERROR - Failed to access form: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.61)
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646D3DB4F]
	(No symbol) [0x00007FF646DE1087]
	(No symbol) [0x00007FF646DF8871]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:04:41,439 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96457
[ 2024-04-23 23:04:41,440 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:04:41,440 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:04:41,441 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:04:41,441 ] 94 nihahi50 - INFO - Accessing form, template sequence: 96456
[ 2024-04-23 23:04:41,441 ] 94 nihahi50 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96456
[ 2024-04-23 23:05:45,065 ] 82 benemmai380 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:05:45,067 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96455
[ 2024-04-23 23:05:45,067 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:05:45,068 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:05:45,068 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:05:45,068 ] 94 benemmai380 - INFO - Accessing form, template sequence: 96456
[ 2024-04-23 23:05:45,069 ] 94 benemmai380 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96456
[ 2024-04-23 23:05:46,661 ] 82 ble79037 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:05:46,662 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96454
[ 2024-04-23 23:05:46,663 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:05:46,663 ] 94 main_controller - INFO - Customer info index 1: {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:05:46,663 ] 94 main_controller - INFO - Customer index 1: Tran Thi Le Lai, M, 19000101, 080-1583-0891, ベトナム
[ 2024-04-23 23:05:46,664 ] 94 ble79037 - INFO - Accessing form, template sequence: 96455
[ 2024-04-23 23:05:46,664 ] 94 ble79037 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96455
[ 2024-04-23 23:05:47,726 ] 82 nihahi50 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:05:47,727 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96456
[ 2024-04-23 23:05:47,728 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:05:47,728 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:05:47,729 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:05:47,729 ] 94 nihahi50 - INFO - Accessing form, template sequence: 96453
[ 2024-04-23 23:05:47,729 ] 94 nihahi50 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453
[ 2024-04-23 23:06:51,150 ] 82 benemmai380 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:06:51,152 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96456
[ 2024-04-23 23:06:51,153 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:06:51,153 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:06:51,154 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:06:51,154 ] 94 benemmai380 - INFO - Accessing form, template sequence: 96453
[ 2024-04-23 23:06:51,154 ] 94 benemmai380 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453
[ 2024-04-23 23:06:52,817 ] 82 ble79037 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:06:52,819 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96455
[ 2024-04-23 23:06:52,820 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:06:52,820 ] 94 main_controller - INFO - Customer info index 1: {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:06:52,821 ] 94 main_controller - INFO - Customer index 1: Tran Thi Le Lai, M, 19000101, 080-1583-0891, ベトナム
[ 2024-04-23 23:06:52,821 ] 94 ble79037 - INFO - Accessing form, template sequence: 96457
[ 2024-04-23 23:06:52,821 ] 94 ble79037 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96457
[ 2024-04-23 23:06:53,835 ] 82 nihahi50 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:06:53,838 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96453
[ 2024-04-23 23:06:53,838 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:06:53,839 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:06:53,839 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:06:53,840 ] 94 nihahi50 - INFO - Accessing form, template sequence: 96455
[ 2024-04-23 23:06:53,840 ] 94 nihahi50 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96455
[ 2024-04-23 23:07:57,299 ] 82 benemmai380 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67564]
	(No symbol) [0x00007FF646DB5F9D]
	(No symbol) [0x00007FF646DB606C]
	(No symbol) [0x00007FF646DFBDD7]
	(No symbol) [0x00007FF646DD9DEF]
	(No symbol) [0x00007FF646DF91C4]
	(No symbol) [0x00007FF646DD9B53]
	(No symbol) [0x00007FF646DA813C]
	(No symbol) [0x00007FF646DA8D71]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646EA9854]
	(No symbol) [0x00007FF646EA99E2]
	(No symbol) [0x00007FF646E9A574]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 76, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:07:57,301 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96453
[ 2024-04-23 23:07:57,301 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:07:57,301 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:07:57,302 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:07:57,302 ] 94 benemmai380 - INFO - Accessing form, template sequence: 96454
[ 2024-04-23 23:07:57,303 ] 94 benemmai380 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454
[ 2024-04-23 23:07:58,994 ] 82 ble79037 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:07:58,996 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96457
[ 2024-04-23 23:07:58,996 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:07:58,997 ] 94 main_controller - INFO - Customer info index 1: {'first_name': 'Thi Le Lai', 'last_name': 'Tran', 'date_birth': '19000101', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:07:58,997 ] 94 main_controller - INFO - Customer index 1: Tran Thi Le Lai, M, 19000101, 080-1583-0891, ベトナム
[ 2024-04-23 23:07:58,997 ] 94 ble79037 - INFO - Accessing form, template sequence: 96453
[ 2024-04-23 23:07:58,998 ] 94 ble79037 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96453
[ 2024-04-23 23:08:00,093 ] 82 nihahi50 - ERROR - Failed to access form: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 21, in fill
    browser.get(form_info.url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3739, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\browser_launcher.py", line 363, in uc_special_open_if_cf
    driver.execute_script('window.open("%s","_blank");' % url)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF6471FF922+3045234]
	(No symbol) [0x00007FF646EA3652]
	(No symbol) [0x00007FF646D67393]
	(No symbol) [0x00007FF646DA74F7]
	(No symbol) [0x00007FF646DD9C59]
	(No symbol) [0x00007FF646DD3FEC]
	(No symbol) [0x00007FF646DD3997]
	(No symbol) [0x00007FF646D332A5]
	GetHandleVerifier [0x00007FF64722E89D+3237613]
	GetHandleVerifier [0x00007FF647270BA7+3508727]
	GetHandleVerifier [0x00007FF64726976F+3478975]
	GetHandleVerifier [0x00007FF646FDF1C6+815126]
	(No symbol) [0x00007FF646EAED0F]
	(No symbol) [0x00007FF646D322DC]
	GetHandleVerifier [0x00007FF6472C5158+3854248]
	BaseThreadInitThunk [0x00007FF92E12257D+29]
	RtlUserThreadStart [0x00007FF93022AA48+40]

[ 2024-04-23 23:08:00,094 ] 94 main_controller - INFO - Failed to fill form, template sequence: 96455
[ 2024-04-23 23:08:00,094 ] 94 main_controller - INFO - Remaining form(s): 5
[ 2024-04-23 23:08:00,095 ] 94 main_controller - INFO - Customer info index 0: {'first_name': 'Van Long', 'last_name': 'Luong', 'date_birth': '19920205', 'phone_number': '080-1583-0891', 'nation': 'ベトナム', 'country': 'ベトナム', 'gender': 'M'}
[ 2024-04-23 23:08:00,095 ] 94 main_controller - INFO - Customer index 0: Luong Van Long, M, 19920205, 080-1583-0891, ベトナム
[ 2024-04-23 23:08:00,095 ] 94 nihahi50 - INFO - Accessing form, template sequence: 96454
[ 2024-04-23 23:08:00,096 ] 94 nihahi50 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=96454
