[ 2024-04-23 22:56:36,667 ] 94 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-23 22:56:36,668 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: nihahi50@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:38,685 ] 94 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-23 22:56:38,685 ] 94 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-23 22:56:38,686 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: ble79037@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:38,686 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: ble79037@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:40,709 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-23 22:56:40,709 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-23 22:56:40,709 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-23 22:56:40,722 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: benemmai380@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:40,722 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: benemmai380@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:40,722 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: benemmai380@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:44,753 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:44,753 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:44,753 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:51,089 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:51,089 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:51,089 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:53,651 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:53,651 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:53,651 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:59,209 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:56:59,209 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:56:59,209 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:56:59,690 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:56:59,690 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:56:59,690 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:56:59,691 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:56:59,691 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:56:59,691 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:02,127 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:02,127 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:02,127 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:02,633 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:02,633 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:02,633 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:02,634 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:02,634 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:02,634 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:02,659 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:02,659 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:02,659 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:02,677 ] 94 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-23 22:57:02,677 ] 94 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-23 22:57:02,677 ] 94 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-23 22:57:02,677 ] 94 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-23 22:57:04,663 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:04,663 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:04,663 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:04,663 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:05,191 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:05,191 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:05,191 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:05,191 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:06,329 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:06,329 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:06,329 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:06,329 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:06,330 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:06,330 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:06,330 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:06,330 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:07,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:07,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:07,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:07,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:07,637 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-23 22:57:07,637 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-23 22:57:07,637 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-23 22:57:07,637 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-23 22:57:07,637 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-23 22:57:09,977 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:09,977 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:09,977 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:09,977 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:09,977 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
