[ 2024-04-23 22:56:36,658 ] 94 root - INFO - Starting all threads
[ 2024-04-23 22:56:36,658 ] 94 root - INFO - Starting all threads
[ 2024-04-23 22:56:36,658 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Hirabari', 'test_mode': False, 'onlyday': False, 'max_num_retry': 5, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': True, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-23 22:56:36,658 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Hirabari', 'test_mode': False, 'onlyday': False, 'max_num_retry': 5, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': True, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-23 22:56:36,659 ] 94 root - INFO - Number of dev accounts: 3
[ 2024-04-23 22:56:36,659 ] 94 root - INFO - Number of dev accounts: 3
[ 2024-04-23 22:56:36,667 ] 94 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-23 22:56:36,668 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: nihahi50@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:38,665 ] 94 root - INFO - Thread 0 started
[ 2024-04-23 22:56:38,665 ] 94 root - INFO - Thread 0 started
[ 2024-04-23 22:56:38,685 ] 94 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-23 22:56:38,686 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: ble79037@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:40,683 ] 94 root - INFO - Thread 1 started
[ 2024-04-23 22:56:40,683 ] 94 root - INFO - Thread 1 started
[ 2024-04-23 22:56:40,709 ] 94 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-23 22:56:40,722 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: benemmai380@gmail.com, Password: hoahong1234
[ 2024-04-23 22:56:42,704 ] 94 root - INFO - Thread 2 started
[ 2024-04-23 22:56:42,704 ] 94 root - INFO - Thread 2 started
[ 2024-04-23 22:56:44,753 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:51,089 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:51,561 ] 94 benemmai380 - INFO - Opened login page
[ 2024-04-23 22:56:53,651 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:56:57,468 ] 94 ble79037 - INFO - Opened login page
[ 2024-04-23 22:56:58,846 ] 94 benemmai380 - INFO - Logging in
[ 2024-04-23 22:56:58,895 ] 94 benemmai380 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:56:59,208 ] 94 benemmai380 - INFO - Logged in finished
[ 2024-04-23 22:56:59,209 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:56:59,690 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:56:59,691 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:56:59,696 ] 94 benemmai380 - INFO - On main page
[ 2024-04-23 22:57:00,660 ] 94 nihahi50 - INFO - Opened login page
[ 2024-04-23 22:57:01,622 ] 94 benemmai380 - INFO - Search submitted
[ 2024-04-23 22:57:01,753 ] 94 benemmai380 - INFO - Collected 20 forms
[ 2024-04-23 22:57:01,762 ] 94 ble79037 - INFO - Logging in
[ 2024-04-23 22:57:01,807 ] 94 ble79037 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:02,125 ] 94 ble79037 - INFO - Logged in finished
[ 2024-04-23 22:57:02,127 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:02,633 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:02,634 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:02,640 ] 94 ble79037 - INFO - On main page
[ 2024-04-23 22:57:02,656 ] 94 benemmai380 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:02,659 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:02,677 ] 94 main_controller - INFO - Subprocess 2 started with trial number 1
[ 2024-04-23 22:57:04,651 ] 94 ble79037 - INFO - Search submitted
[ 2024-04-23 22:57:04,663 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:04,799 ] 94 nihahi50 - INFO - Logging in
[ 2024-04-23 22:57:04,850 ] 94 ble79037 - INFO - Collected 20 forms
[ 2024-04-23 22:57:04,852 ] 94 nihahi50 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:05,190 ] 94 nihahi50 - INFO - Logged in finished
[ 2024-04-23 22:57:05,191 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:06,329 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:06,330 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:06,379 ] 94 nihahi50 - INFO - On main page
[ 2024-04-23 22:57:07,625 ] 94 ble79037 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:07,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:07,637 ] 94 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-23 22:57:08,559 ] 94 nihahi50 - INFO - Search submitted
[ 2024-04-23 22:57:08,633 ] 94 nihahi50 - INFO - Collected 20 forms
[ 2024-04-23 22:57:09,975 ] 94 nihahi50 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:09,977 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:09,982 ] 94 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-23 22:57:10,833 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:11,779 ] 94 benemmai380 - INFO - Opened login page
[ 2024-04-23 22:57:14,480 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:16,050 ] 94 benemmai380 - INFO - Logging in
[ 2024-04-23 22:57:16,071 ] 94 benemmai380 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:16,431 ] 94 benemmai380 - INFO - Logged in finished
[ 2024-04-23 22:57:16,432 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:17,388 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:17,392 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:17,439 ] 94 benemmai380 - INFO - On main page
[ 2024-04-23 22:57:18,065 ] 94 ble79037 - INFO - Opened login page
[ 2024-04-23 22:57:20,293 ] 94 benemmai380 - INFO - Search submitted
[ 2024-04-23 22:57:20,438 ] 94 benemmai380 - INFO - Collected 20 forms
[ 2024-04-23 22:57:21,367 ] 94 benemmai380 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:21,368 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:21,435 ] 94 main_controller - INFO - Subprocess 2 started with trial number 2
[ 2024-04-23 22:57:21,459 ] 94 nihahi50 - INFO - Opened login page
[ 2024-04-23 22:57:22,447 ] 94 ble79037 - INFO - Logging in
[ 2024-04-23 22:57:22,465 ] 94 ble79037 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:22,780 ] 94 ble79037 - INFO - Logged in finished
[ 2024-04-23 22:57:22,782 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:23,378 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:23,380 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:23,389 ] 94 ble79037 - INFO - On main page
[ 2024-04-23 22:57:25,049 ] 94 ble79037 - INFO - Search submitted
[ 2024-04-23 22:57:25,130 ] 94 ble79037 - INFO - Collected 20 forms
[ 2024-04-23 22:57:25,420 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:25,427 ] 94 nihahi50 - INFO - Logging in
[ 2024-04-23 22:57:25,442 ] 94 nihahi50 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:25,780 ] 94 nihahi50 - INFO - Logged in finished
[ 2024-04-23 22:57:25,780 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:26,588 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:57:26,592 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:26,619 ] 94 ble79037 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:26,628 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:26,640 ] 94 main_controller - INFO - Subprocess 1 started with trial number 2
[ 2024-04-23 22:57:26,699 ] 94 nihahi50 - INFO - On main page
[ 2024-04-23 22:57:28,502 ] 94 nihahi50 - INFO - Search submitted
[ 2024-04-23 22:57:28,575 ] 94 nihahi50 - INFO - Collected 20 forms
[ 2024-04-23 22:57:30,376 ] 94 nihahi50 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:30,378 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:30,383 ] 94 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-23 22:57:31,876 ] 94 benemmai380 - INFO - Opened login page
[ 2024-04-23 22:57:32,061 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:38,020 ] 94 benemmai380 - INFO - Logging in
[ 2024-04-23 22:57:38,061 ] 94 benemmai380 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:38,384 ] 94 benemmai380 - INFO - Logged in finished
[ 2024-04-23 22:57:38,385 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:39,389 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_benemmai380.png
[ 2024-04-23 22:57:39,394 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:39,531 ] 94 benemmai380 - INFO - On main page
[ 2024-04-23 22:57:41,498 ] 94 ble79037 - INFO - Opened login page
[ 2024-04-23 22:57:43,086 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:57:44,099 ] 94 benemmai380 - INFO - Search submitted
[ 2024-04-23 22:57:44,722 ] 94 benemmai380 - INFO - Collected 20 forms
[ 2024-04-23 22:57:48,195 ] 94 benemmai380 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:48,199 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:48,214 ] 94 main_controller - INFO - Subprocess 2 started with trial number 3
[ 2024-04-23 22:57:51,321 ] 94 ble79037 - INFO - Logging in
[ 2024-04-23 22:57:51,353 ] 94 ble79037 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:57:51,682 ] 94 ble79037 - INFO - Logged in finished
[ 2024-04-23 22:57:51,684 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:57:54,501 ] 94 nihahi50 - INFO - Opened login page
[ 2024-04-23 22:57:55,558 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_ble79037.png
[ 2024-04-23 22:57:55,561 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:57:55,595 ] 94 ble79037 - INFO - On main page
[ 2024-04-23 22:57:57,585 ] 94 ble79037 - INFO - Search submitted
[ 2024-04-23 22:57:57,639 ] 94 ble79037 - INFO - Collected 20 forms
[ 2024-04-23 22:57:58,500 ] 94 ble79037 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:57:58,503 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:57:58,531 ] 94 main_controller - INFO - Subprocess 1 started with trial number 3
[ 2024-04-23 22:57:59,671 ] 94 nihahi50 - INFO - Logging in
[ 2024-04-23 22:57:59,679 ] 94 nihahi50 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-23 22:58:00,049 ] 94 nihahi50 - INFO - Logged in finished
[ 2024-04-23 22:58:00,075 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-23 22:58:00,161 ] 94 main_controller - INFO - Browser opened
[ 2024-04-23 22:58:01,575 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_23\22_56_34\screenshot_nihahi50.png
[ 2024-04-23 22:58:01,577 ] 94 main_controller - INFO - Finding forms
[ 2024-04-23 22:58:01,602 ] 94 nihahi50 - INFO - On main page
[ 2024-04-23 22:58:04,098 ] 94 nihahi50 - INFO - Search submitted
[ 2024-04-23 22:58:04,378 ] 94 nihahi50 - INFO - Collected 20 forms
[ 2024-04-23 22:58:06,086 ] 94 nihahi50 - INFO - Number of filtered forms left is: 5 form(s)
[ 2024-04-23 22:58:06,091 ] 82 main_controller - ERROR - Caught exception: sequence item 0: expected str instance, FormInfo found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 72, in subprocess
    list_form_info = finder.find(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 23, in find
    self._collect(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\finder.py", line 78, in _collect
    self.logger.info(form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 70, in info
    self._log(logging.INFO, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 93, in _log
    message = " ".join(msg)
TypeError: sequence item 0: expected str instance, FormInfo found
[ 2024-04-23 22:58:06,102 ] 94 main_controller - INFO - Subprocess 0 started with trial number 3
